/**
 * Component catalog.
 *
 * Specs were researched from manufacturer datasheets on 2026-07-20. Each part
 * carries a `source` with the datasheet URL and a confidence rating. Anything
 * the research could not verify is `null` — never a guess — and the NEC engine
 * reports "unknown" rather than calculating on a null.
 *
 * This is a point-in-time snapshot. Datasheets get revised, SKUs get
 * superseded, and prices move constantly. Confirm against a live datasheet
 * before ordering or submitting for permit. See VERIFICATION.md.
 */

import type {
  Battery,
  BosPart,
  ChargeController,
  Evse,
  Inverter,
  LoadCenter,
  Mount,
  PvModule,
} from '../types'

import modulesData from './modules.json'
import invertersData from './inverters.json'

const modules = modulesData as unknown as PvModule[]
const inverters = invertersData as unknown as Inverter[]

/**
 * Inverters whose optimizers hold the string at a fixed voltage.
 *
 * These break the usual NEC 690.7 string-sizing model: because each optimizer
 * regulates its own output, string length is bounded by *optimizer count*, not
 * by cold-temperature Voc. Sizing one of these with the temperature-correction
 * method produces a wrong answer, so the engine branches on this set.
 */
export const OPTIMIZER_BASED_INVERTERS = new Set(['solaredge'])

export interface OptimizerStringLimits {
  min_per_string: number
  max_per_string: number
  /**
   * Beyond this count the accumulated per-optimizer standby voltage
   * (~1 V each) breaches the NEC 690.12 30 V rapid-shutdown limit.
   */
  rapid_shutdown_max: number
}

/** SolarEdge optimizer-count limits, from the S-Series/U-Series datasheets. */
export const SOLAREDGE_STRING_LIMITS: Record<string, OptimizerStringLimits> = {
  'single-phase': { min_per_string: 6, max_per_string: 25, rapid_shutdown_max: 27 },
  'three-phase-208': { min_per_string: 8, max_per_string: 50, rapid_shutdown_max: 27 },
  'three-phase-480': { min_per_string: 14, max_per_string: 50, rapid_shutdown_max: 27 },
}

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------

const batteries: Battery[] = [
  {
    id: 'tesla-powerwall-3',
    manufacturer: 'Tesla',
    model: 'Powerwall 3',
    chemistry: 'LFP',
    nominal_voltage_v: 240,
    usable_capacity_kwh: 13.5,
    total_capacity_kwh: null,
    max_continuous_discharge_kw: 11.5,
    max_continuous_discharge_a: 48,
    peak_power_kw: null,
    peak_duration_s: null,
    max_charge_current_a: 20.8,
    round_trip_efficiency_pct: 89,
    coupling: 'AC',
    max_units_stackable: 4,
    operating_temp_min_c: -20,
    operating_temp_max_c: 50,
    listings: ['UL 1741', 'UL 9540', 'UL 9540A', 'UL 3741', 'UL 1973'],
    enclosure_rating: 'NEMA 3R / IP67',
    outdoor_rated: true,
    width_mm: 609,
    height_mm: 1105,
    depth_mm: 193,
    weight_kg: 132,
    warranty_yr: 10,
    warranty_throughput_mwh: null,
    price_usd: null,
    source: {
      url: 'https://energylibrary.tesla.com/docs/Public/EnergyStorage/Powerwall/3/Datasheet/en-us/Powerwall-3-Datasheet.pdf',
      retrieved: '2026-07-20',
      confidence: 'medium',
      note: 'Output is configurable across 5.8 / 7.6 / 10 / 11.5 kW tiers; the 11.5 kW figure needs an 80 A breaker. Tesla publishes no separate battery-only round-trip efficiency — 89% is the solar-to-battery-to-home figure. A widely repeated "22 kW peak" appears nowhere in Tesla documentation. Retrieved via mirror; tesla.com blocks automated fetch.',
    },
  },
  {
    id: 'enphase-iq-battery-5p',
    manufacturer: 'Enphase',
    model: 'IQ Battery 5P',
    chemistry: 'LFP',
    nominal_voltage_v: 240,
    usable_capacity_kwh: 5.0,
    total_capacity_kwh: 5.0,
    max_continuous_discharge_kw: 3.84,
    max_continuous_discharge_a: 16,
    peak_power_kw: 7.68,
    peak_duration_s: 3,
    max_charge_current_a: null,
    round_trip_efficiency_pct: 90,
    coupling: 'AC',
    max_units_stackable: null,
    operating_temp_min_c: -20,
    operating_temp_max_c: 55,
    listings: ['UL 9540', 'UL 9540A', 'UL 1973'],
    enclosure_rating: 'NEMA 3R',
    outdoor_rated: true,
    width_mm: 550,
    height_mm: 980,
    depth_mm: 188,
    weight_kg: 78.9,
    warranty_yr: 15,
    warranty_throughput_mwh: null,
    price_usd: null,
    source: {
      url: 'https://enphase.com/download/iq-battery-5p-data-sheet',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: 'One unit per 20 A branch circuit. 90% AC / 96% DC round-trip. Warranty is 15 yr or 6000 cycles, whichever comes first.',
    },
  },
  {
    id: 'enphase-iq-battery-10c',
    manufacturer: 'Enphase',
    model: 'IQ Battery 10C',
    chemistry: 'LFP',
    nominal_voltage_v: 240,
    usable_capacity_kwh: 10.0,
    total_capacity_kwh: 10.0,
    max_continuous_discharge_kw: 7.08,
    max_continuous_discharge_a: 29.5,
    peak_power_kw: 13.44,
    peak_duration_s: 3,
    max_charge_current_a: null,
    round_trip_efficiency_pct: 90,
    coupling: 'AC',
    max_units_stackable: null,
    operating_temp_min_c: -20,
    operating_temp_max_c: 55,
    listings: ['UL 9540', 'UL 9540A', 'UL 1973'],
    enclosure_rating: 'NEMA 3R',
    outdoor_rated: true,
    width_mm: 708,
    height_mm: 621,
    depth_mm: 365,
    weight_kg: 144,
    warranty_yr: 15,
    warranty_throughput_mwh: null,
    price_usd: null,
    source: {
      url: 'https://enphase.com/download/iq-battery-10c-data-sheet',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: 'The 10C and the older 10T are different products, not two names for one SKU: the 10C delivers 7.08 kW continuous against the 10T’s 3.84 kW at the same ~10 kWh.',
    },
  },
  {
    id: 'eg4-powerpro-wallmount-aw-280',
    manufacturer: 'EG4',
    model: 'PowerPro WallMount All Weather 280Ah',
    chemistry: 'LFP',
    nominal_voltage_v: 51.2,
    usable_capacity_kwh: 14.3,
    total_capacity_kwh: 14.3,
    max_continuous_discharge_kw: 7.17,
    max_continuous_discharge_a: 140,
    peak_power_kw: 10.2,
    peak_duration_s: 1800,
    max_charge_current_a: 140,
    round_trip_efficiency_pct: null,
    coupling: 'DC',
    max_units_stackable: null,
    operating_temp_min_c: -20,
    operating_temp_max_c: 55,
    listings: ['UL 1973', 'UL 9540A'],
    enclosure_rating: 'IP65',
    outdoor_rated: true,
    width_mm: 566,
    height_mm: 916,
    depth_mm: 232,
    weight_kg: 140,
    warranty_yr: 10,
    warranty_throughput_mwh: null,
    price_usd: 3125,
    source: {
      url: 'https://eg4electronics.com/wp-content/uploads/2024/04/EG4-14.3kWh-PowerPro-WallMount-AW-Spec-Sheet.pdf',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: 'Integrated self-heating (56 V, 224 W). ~$218/kWh at the researched street price. Round-trip efficiency is not published for this SKU.',
    },
  },
  {
    id: 'eg4-wallmount-314-indoor',
    manufacturer: 'EG4',
    model: 'WallMount Indoor 314Ah',
    chemistry: 'LFP',
    nominal_voltage_v: 51.2,
    usable_capacity_kwh: 12.86,
    total_capacity_kwh: 16.0,
    max_continuous_discharge_kw: 10.2,
    max_continuous_discharge_a: 200,
    peak_power_kw: 12.8,
    peak_duration_s: 3,
    max_charge_current_a: 157,
    round_trip_efficiency_pct: 95,
    coupling: 'DC',
    max_units_stackable: 32,
    operating_temp_min_c: -20,
    operating_temp_max_c: 55,
    listings: ['UL 1973', 'UL 9540A', 'UL 9540'],
    enclosure_rating: 'IP20',
    outdoor_rated: false,
    width_mm: 460,
    height_mm: 865,
    depth_mm: 245,
    weight_kg: 133,
    warranty_yr: 10,
    warranty_throughput_mwh: null,
    price_usd: null,
    source: {
      url: 'https://eg4electronics.com/wp-content/uploads/2025/10/EG4-WallMount-314Ah-Indoor-Battery-Spec-Sheet.pdf',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: 'Indoor only (IP20). Warranty 10 yr or 10,000 cycles. Usable figure is at the recommended 80% DoD.',
    },
  },
  {
    id: 'pytes-v5',
    manufacturer: 'Pytes',
    model: 'V5',
    chemistry: 'LFP',
    nominal_voltage_v: 51.2,
    usable_capacity_kwh: 5.12,
    total_capacity_kwh: 5.12,
    max_continuous_discharge_kw: 5.12,
    max_continuous_discharge_a: 100,
    peak_power_kw: 9.2,
    peak_duration_s: 15,
    max_charge_current_a: 100,
    round_trip_efficiency_pct: 95,
    coupling: 'DC',
    max_units_stackable: 16,
    operating_temp_min_c: -10,
    operating_temp_max_c: 50,
    listings: ['UL 9540', 'UL 9540A', 'UL 1973', 'CEC', 'SGIP'],
    enclosure_rating: null,
    outdoor_rated: false,
    width_mm: 424,
    height_mm: 140,
    depth_mm: 530,
    weight_kg: 44,
    warranty_yr: 10,
    warranty_throughput_mwh: null,
    price_usd: 1350,
    source: {
      url: 'https://www.pytesusa.com/Low-Voltage-Battery/v5.html',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: 'Server-rack format. 16 units per group, 6 groups (492 kWh) with the Pytes Hub. Peak current is de-rated outside 10-40 degC. Street price $1250-1450.',
    },
  },
  {
    id: 'fortress-evault-max-18-5',
    manufacturer: 'Fortress Power',
    model: 'eVault MAX 18.5',
    chemistry: 'LFP',
    nominal_voltage_v: 51.2,
    usable_capacity_kwh: 18.43,
    total_capacity_kwh: 18.43,
    max_continuous_discharge_kw: 9.2,
    max_continuous_discharge_a: 180,
    peak_power_kw: 12.8,
    peak_duration_s: 5,
    max_charge_current_a: 180,
    round_trip_efficiency_pct: 98,
    coupling: 'DC',
    max_units_stackable: 20,
    operating_temp_min_c: -20,
    operating_temp_max_c: 60,
    listings: ['UL 1642', 'UL 1973', 'UL 9540', 'UL 9540A'],
    enclosure_rating: 'IP55',
    outdoor_rated: true,
    width_mm: 515,
    height_mm: 1073,
    depth_mm: 515,
    weight_kg: 236,
    warranty_yr: 10,
    warranty_throughput_mwh: null,
    price_usd: 6950,
    source: {
      url: 'https://www.fortresspower.com/wp-content/uploads/2022/05/eVault-MAX-18.5-technical-datasheet.pdf',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: '8000 cycles at 80% DoD. Up to 20 units (370 kWh). One distributor indicated the line is being phased out for eBoost — confirm availability before quoting.',
    },
  },
  {
    id: 'discover-helios-ess-16',
    manufacturer: 'Discover Energy Systems',
    model: 'HELIOS ESS 52-48-16000',
    chemistry: 'LFP',
    nominal_voltage_v: 51.2,
    usable_capacity_kwh: 16.08,
    total_capacity_kwh: 16.08,
    max_continuous_discharge_kw: 10.24,
    max_continuous_discharge_a: 200,
    peak_power_kw: 15.4,
    peak_duration_s: 15,
    max_charge_current_a: 200,
    round_trip_efficiency_pct: null,
    coupling: 'DC',
    max_units_stackable: 36,
    operating_temp_min_c: -25,
    operating_temp_max_c: 55,
    listings: ['UL 1973', 'UL 9540A', 'UL 9540 DC ESS 3rd Ed.'],
    enclosure_rating: 'IP65 / NEMA 3R',
    outdoor_rated: true,
    width_mm: 465,
    height_mm: 900,
    depth_mm: 247,
    weight_kg: 136,
    warranty_yr: 10,
    warranty_throughput_mwh: 93,
    price_usd: null,
    source: {
      url: 'https://discoverenergysys.com/s4x_files/resources/808-0046-helios-datasheet.pdf',
      retrieved: '2026-07-20',
      confidence: 'high',
      note: 'Warranty is a 93 MWh throughput guarantee rather than a cycle count. Self-heating from -25 to 8 degC. Quote-only; no public pricing.',
    },
  },
]

// ---------------------------------------------------------------------------
// Charge controllers (off-grid)
// ---------------------------------------------------------------------------

const chargeControllers: ChargeController[] = [
  {
    id: 'victron-smartsolar-150-45',
    manufacturer: 'Victron',
    model: 'SmartSolar MPPT 150/45',
    type: 'MPPT',
    max_pv_input_voltage_v: 150,
    max_charge_current_a: 45,
    max_pv_power_w_by_battery_v: { '12': 650, '24': 1300, '48': 2600 },
    battery_voltages_v: [12, 24, 48],
    efficiency_pct: 98,
    price_usd: 400,
    source: { url: 'https://www.victronenergy.com/solar-charge-controllers', retrieved: '2026-07-20', confidence: 'medium' },
  },
  {
    id: 'victron-smartsolar-250-100',
    manufacturer: 'Victron',
    model: 'SmartSolar MPPT 250/100',
    type: 'MPPT',
    max_pv_input_voltage_v: 250,
    max_charge_current_a: 100,
    max_pv_power_w_by_battery_v: { '12': 1450, '24': 2900, '48': 5800 },
    battery_voltages_v: [12, 24, 48],
    efficiency_pct: 98,
    price_usd: 850,
    source: { url: 'https://www.victronenergy.com/solar-charge-controllers', retrieved: '2026-07-20', confidence: 'medium' },
  },
  {
    id: 'midnite-classic-150',
    manufacturer: 'MidNite Solar',
    model: 'Classic 150',
    type: 'MPPT',
    max_pv_input_voltage_v: 150,
    max_charge_current_a: 96,
    max_pv_power_w_by_battery_v: { '12': 1200, '24': 2400, '48': 4800 },
    battery_voltages_v: [12, 24, 48],
    efficiency_pct: 97,
    price_usd: 700,
    source: { url: 'https://www.midnitesolar.com/', retrieved: '2026-07-20', confidence: 'low', note: 'Specs not confirmed against a fetched datasheet this pass. Verify before use.' },
  },
]

// ---------------------------------------------------------------------------
// Mounting
// ---------------------------------------------------------------------------

const mounts: Mount[] = [
  {
    id: 'ironridge-xr10-flashfoot2',
    manufacturer: 'IronRidge',
    product_line: 'XR10 rail + FlashFoot 2',
    kind: 'roof',
    roof_types: ['comp-shingle'],
    tracking_axes: 0,
    tracking_range_deg: null,
    backtracking: null,
    tilt_min_deg: null,
    tilt_max_deg: null,
    max_rail_span_mm: 1800,
    max_cantilever_mm: 600,
    load_basis: 'ASCE 7-16 / 7-22',
    ul2703_listed: true,
    integrated_bonding: true,
    modules_per_table: null,
    foundation: null,
    cost_usd_per_module: 55,
    cost_usd_per_w: null,
    source: { url: 'https://www.ironridge.com/', retrieved: '2026-07-20', confidence: 'low', note: 'Span and cost figures are planning estimates. Run IronRidge Design Assistant for the actual span table at your wind/snow loads.' },
  },
  {
    id: 'ironridge-xr100-tile',
    manufacturer: 'IronRidge',
    product_line: 'XR100 rail + tile hook',
    kind: 'roof',
    roof_types: ['tile'],
    tracking_axes: 0,
    tracking_range_deg: null,
    backtracking: null,
    tilt_min_deg: null,
    tilt_max_deg: null,
    max_rail_span_mm: 2400,
    max_cantilever_mm: 800,
    load_basis: 'ASCE 7-16 / 7-22',
    ul2703_listed: true,
    integrated_bonding: true,
    modules_per_table: null,
    foundation: null,
    cost_usd_per_module: 85,
    cost_usd_per_w: null,
    source: { url: 'https://www.ironridge.com/', retrieved: '2026-07-20', confidence: 'low', note: 'Planning estimates — verify span tables.' },
  },
  {
    id: 's5-standing-seam',
    manufacturer: 'S-5!',
    product_line: 'S-5! clamp + PVKIT (rail-less)',
    kind: 'roof',
    roof_types: ['standing-seam-metal'],
    tracking_axes: 0,
    tracking_range_deg: null,
    backtracking: null,
    tilt_min_deg: null,
    tilt_max_deg: null,
    max_rail_span_mm: null,
    max_cantilever_mm: null,
    load_basis: 'ASCE 7-16',
    ul2703_listed: true,
    integrated_bonding: true,
    modules_per_table: null,
    foundation: null,
    cost_usd_per_module: 45,
    cost_usd_per_w: null,
    source: { url: 'https://www.s-5.com/', retrieved: '2026-07-20', confidence: 'low', note: 'No roof penetration — clamps to the seam. Cost is a planning estimate.' },
  },
  {
    id: 'unirac-rm10-ballasted',
    manufacturer: 'Unirac',
    product_line: 'RM10 ballasted',
    kind: 'roof',
    roof_types: ['flat-membrane'],
    tracking_axes: 0,
    tracking_range_deg: null,
    backtracking: null,
    tilt_min_deg: 10,
    tilt_max_deg: 10,
    max_rail_span_mm: null,
    max_cantilever_mm: null,
    load_basis: 'ASCE 7-16',
    ul2703_listed: true,
    integrated_bonding: true,
    modules_per_table: null,
    foundation: 'ballast blocks',
    cost_usd_per_module: 70,
    cost_usd_per_w: null,
    source: { url: 'https://unirac.com/', retrieved: '2026-07-20', confidence: 'low', note: 'Ballast weight must be engineered against the roof structure — this tool does not size ballast.' },
  },
  {
    id: 'ironridge-ground-mount',
    manufacturer: 'IronRidge',
    product_line: 'Ground Mount System',
    kind: 'ground-fixed',
    roof_types: ['ground'],
    tracking_axes: 0,
    tracking_range_deg: null,
    backtracking: null,
    tilt_min_deg: 10,
    tilt_max_deg: 45,
    max_rail_span_mm: 2400,
    max_cantilever_mm: 800,
    load_basis: 'ASCE 7-16',
    ul2703_listed: true,
    integrated_bonding: true,
    modules_per_table: 20,
    foundation: 'concrete pier or driven pile',
    cost_usd_per_module: null,
    cost_usd_per_w: 0.22,
    source: { url: 'https://www.ironridge.com/', retrieved: '2026-07-20', confidence: 'low', note: 'Foundation design requires a geotechnical assessment. Planning estimates only.' },
  },
  {
    id: 'array-tech-duratrack-hz-v3',
    manufacturer: 'Array Technologies',
    product_line: 'DuraTrack HZ v3',
    kind: 'tracker',
    roof_types: ['ground'],
    tracking_axes: 1,
    tracking_range_deg: 52,
    backtracking: true,
    tilt_min_deg: null,
    tilt_max_deg: null,
    max_rail_span_mm: null,
    max_cantilever_mm: null,
    load_basis: 'ASCE 7-16',
    ul2703_listed: null,
    integrated_bonding: null,
    modules_per_table: 90,
    foundation: 'driven pile',
    cost_usd_per_module: null,
    cost_usd_per_w: 0.11,
    source: { url: 'https://arraytechinc.com/', retrieved: '2026-07-20', confidence: 'low', note: 'Horizontal single-axis, N-S axis with E-W tracking. Typical energy gain 15-25% over fixed tilt depending on latitude. Utility-scale product; verify minimum project size.' },
  },
  {
    id: 'mt-solar-dual-axis-pole',
    manufacturer: 'MT Solar',
    product_line: 'Dual-axis pole mount',
    kind: 'tracker',
    roof_types: ['ground'],
    tracking_axes: 2,
    tracking_range_deg: 60,
    backtracking: false,
    tilt_min_deg: 0,
    tilt_max_deg: 60,
    max_rail_span_mm: null,
    max_cantilever_mm: null,
    load_basis: 'ASCE 7-16',
    ul2703_listed: null,
    integrated_bonding: null,
    modules_per_table: 12,
    foundation: 'concrete pier',
    cost_usd_per_module: null,
    cost_usd_per_w: 0.45,
    source: { url: 'https://mtsolar.us/', retrieved: '2026-07-20', confidence: 'low', note: 'Small-scale dual-axis for off-grid and residential. Typical energy gain 25-40% over fixed tilt, at meaningfully higher O&M.' },
  },
]

// ---------------------------------------------------------------------------
// EV charging
// ---------------------------------------------------------------------------

const evse: Evse[] = [
  {
    id: 'tesla-wall-connector-gen3',
    manufacturer: 'Tesla',
    model: 'Wall Connector (Gen 3 Universal)',
    connector: 'dual',
    max_output_a: 48,
    max_output_kw: 11.5,
    adjustable_output_a: [12, 16, 20, 24, 32, 40, 48],
    required_breaker_a: 60,
    hardwired: true,
    plug_type: null,
    nema_rating: 'NEMA 3R',
    indoor_outdoor: 'both',
    load_management: true,
    bidirectional_v2h: false,
    solar_excess_charging: false,
    ul_listed: true,
    price_usd: 620,
    source: { url: 'https://www.tesla.com/support/home-charging-installation/wall-connector', retrieved: '2026-07-20', confidence: 'medium', note: 'Power sharing across up to 6 units acts as load management under 625.42.' },
  },
  {
    id: 'enphase-iq-ev-charger-2',
    manufacturer: 'Enphase',
    model: 'IQ EV Charger 2',
    connector: 'J1772',
    max_output_a: 48,
    max_output_kw: 11.5,
    adjustable_output_a: [16, 24, 32, 40, 48],
    required_breaker_a: 60,
    hardwired: true,
    plug_type: null,
    nema_rating: 'NEMA 4',
    indoor_outdoor: 'both',
    load_management: true,
    bidirectional_v2h: false,
    solar_excess_charging: true,
    ul_listed: true,
    price_usd: 700,
    source: { url: 'https://enphase.com/ev-chargers', retrieved: '2026-07-20', confidence: 'medium', note: 'Integrates with Enphase monitoring for excess-solar charging.' },
  },
  {
    id: 'chargepoint-home-flex',
    manufacturer: 'ChargePoint',
    model: 'Home Flex',
    connector: 'J1772',
    max_output_a: 50,
    max_output_kw: 12,
    adjustable_output_a: [16, 20, 24, 32, 40, 48, 50],
    required_breaker_a: 60,
    hardwired: true,
    plug_type: 'NEMA 14-50 (plug-in variant)',
    nema_rating: 'NEMA 3R',
    indoor_outdoor: 'both',
    load_management: true,
    bidirectional_v2h: false,
    solar_excess_charging: false,
    ul_listed: true,
    price_usd: 550,
    source: { url: 'https://www.chargepoint.com/drivers/home', retrieved: '2026-07-20', confidence: 'medium' },
  },
  {
    id: 'wallbox-pulsar-plus',
    manufacturer: 'Wallbox',
    model: 'Pulsar Plus',
    connector: 'J1772',
    max_output_a: 40,
    max_output_kw: 9.6,
    adjustable_output_a: [16, 24, 32, 40],
    required_breaker_a: 50,
    hardwired: true,
    plug_type: 'NEMA 14-50 (plug-in variant)',
    nema_rating: 'NEMA 4',
    indoor_outdoor: 'both',
    load_management: true,
    bidirectional_v2h: false,
    solar_excess_charging: true,
    ul_listed: true,
    price_usd: 650,
    source: { url: 'https://wallbox.com/en_us/wallbox-pulsar-plus', retrieved: '2026-07-20', confidence: 'medium' },
  },
  {
    id: 'emporia-level-2',
    manufacturer: 'Emporia',
    model: 'Level 2 EV Charger',
    connector: 'J1772',
    max_output_a: 48,
    max_output_kw: 11.5,
    adjustable_output_a: [16, 24, 32, 40, 48],
    required_breaker_a: 60,
    hardwired: true,
    plug_type: 'NEMA 14-50 (plug-in variant)',
    nema_rating: 'NEMA 4',
    indoor_outdoor: 'both',
    load_management: true,
    bidirectional_v2h: false,
    solar_excess_charging: true,
    ul_listed: true,
    price_usd: 400,
    source: { url: 'https://www.emporiaenergy.com/ev-charger', retrieved: '2026-07-20', confidence: 'medium', note: 'Load management requires the Emporia Vue energy monitor.' },
  },
]

// ---------------------------------------------------------------------------
// Service equipment
// ---------------------------------------------------------------------------

const loadCenters: LoadCenter[] = [
  { id: 'square-d-qo-200', manufacturer: 'Square D', model: 'QO 200A main breaker load center', busbar_rating_a: 225, main_breaker_a: 200, spaces: 42, center_fed: false, supports_whole_home_backup: false, price_usd: 400, source: { url: 'https://www.se.com/us/en/product-range/1461-qo/', retrieved: '2026-07-20', confidence: 'low', note: 'Busbar rating varies by exact catalog number — confirm on the panel label before running the 705.12 calculation.' } },
  { id: 'square-d-qo-125', manufacturer: 'Square D', model: 'QO 125A main breaker load center', busbar_rating_a: 125, main_breaker_a: 125, spaces: 24, center_fed: false, supports_whole_home_backup: false, price_usd: 250, source: { url: 'https://www.se.com/us/en/product-range/1461-qo/', retrieved: '2026-07-20', confidence: 'low' } },
  { id: 'eaton-br-200', manufacturer: 'Eaton', model: 'BR 200A main breaker load center', busbar_rating_a: 200, main_breaker_a: 200, spaces: 40, center_fed: false, supports_whole_home_backup: false, price_usd: 350, source: { url: 'https://www.eaton.com/', retrieved: '2026-07-20', confidence: 'low' } },
  { id: 'span-smart-panel', manufacturer: 'SPAN', model: 'SPAN Smart Panel', busbar_rating_a: 225, main_breaker_a: 200, spaces: 32, center_fed: false, supports_whole_home_backup: true, price_usd: 3500, source: { url: 'https://www.span.io/panel', retrieved: '2026-07-20', confidence: 'low', note: 'Circuit-level control enables whole-home backup with a smaller battery by shedding loads dynamically.' } },
  { id: 'eg4-gridboss', manufacturer: 'EG4', model: 'GridBOSS MID (MI-200-2P-HYB-AW)', busbar_rating_a: 200, main_breaker_a: 200, spaces: null, center_fed: false, supports_whole_home_backup: true, price_usd: 1799, source: { url: 'https://eg4electronics.com/wp-content/uploads/2024/05/EG4%C2%AE-Grid-BOSS-Spec-Sheet.pdf', retrieved: '2026-07-20', confidence: 'high', note: 'Not an inverter — a service-entrance-rated microgrid interconnection device aggregating up to 3 EG4 hybrid inverters. Internal bus is 350 A, software-limited to 200 A. Service-entrance rating requires the specified Eaton 200 A main breaker.' } },
  { id: 'enphase-iq-combiner-5', manufacturer: 'Enphase', model: 'IQ Combiner 5', busbar_rating_a: 125, main_breaker_a: null, spaces: 4, center_fed: false, supports_whole_home_backup: false, price_usd: 800, source: { url: 'https://enphase.com/download/iq-combiner-5-data-sheet', retrieved: '2026-07-20', confidence: 'high', note: 'Combiner/gateway, not service equipment: no main breaker. Max 64 A continuous PV/storage input, 80 A total branch breakers. Breakers sold separately.' } },
]

// ---------------------------------------------------------------------------
// Balance of system
// ---------------------------------------------------------------------------

const bos: BosPart[] = [
  { id: 'pv-wire-10awg', category: 'wire', manufacturer: null, model: 'PV Wire 10 AWG', description: 'PV Wire, 10 AWG, 2000 V, sunlight resistant', unit: 'ft', price_usd: 0.55, specs: { awg: '10', voltage_rating: 2000, temp_rating_c: 90, sunlight_resistant: true, standard: 'UL 4703' } },
  { id: 'pv-wire-12awg', category: 'wire', manufacturer: null, model: 'PV Wire 12 AWG', description: 'PV Wire, 12 AWG, 2000 V, sunlight resistant', unit: 'ft', price_usd: 0.42, specs: { awg: '12', voltage_rating: 2000, temp_rating_c: 90, sunlight_resistant: true, standard: 'UL 4703' } },
  { id: 'thwn2-10awg', category: 'wire', manufacturer: null, model: 'THWN-2 10 AWG Cu', description: 'THWN-2 copper, 10 AWG, 600 V, wet/dry 90 degC', unit: 'ft', price_usd: 0.38, specs: { awg: '10', material: 'Cu', temp_rating_c: 90, standard: 'UL 83' } },
  { id: 'thwn2-6awg', category: 'wire', manufacturer: null, model: 'THWN-2 6 AWG Cu', description: 'THWN-2 copper, 6 AWG, 600 V', unit: 'ft', price_usd: 1.15, specs: { awg: '6', material: 'Cu', temp_rating_c: 90 } },
  { id: 'bare-cu-6awg', category: 'grounding', manufacturer: null, model: 'Bare copper 6 AWG', description: 'Bare stranded copper grounding electrode conductor, 6 AWG', unit: 'ft', price_usd: 1.05, specs: { awg: '6', material: 'Cu' } },
  { id: 'mc4-evo2-pair', category: 'connector', manufacturer: 'Stäubli', model: 'MC4-Evo2', description: 'MC4-Evo2 connector pair, field-installable', unit: 'ea', price_usd: 6.5, specs: { current_rating_a: 45, voltage_rating: 1500, note: 'Do not intermate with other brands of MC4-style connector — NEC 690.33 requires connectors be listed for the combination.' } },
  { id: 'emt-3-4', category: 'conduit', manufacturer: null, model: 'EMT 3/4 in', description: 'Electrical metallic tubing, 3/4 in', unit: 'ft', price_usd: 1.35, specs: { trade_size: '3/4', sunlight_ok: true } },
  { id: 'pvc-sch40-1', category: 'conduit', manufacturer: null, model: 'PVC Sch 40, 1 in', description: 'Rigid PVC conduit schedule 40, 1 in', unit: 'ft', price_usd: 1.1, specs: { trade_size: '1', sunlight_ok: true, note: 'Expansion fittings required on long exposed runs.' } },
  { id: 'ac-disconnect-60a-3r', category: 'disconnect', manufacturer: null, model: 'AC disconnect 60 A NEMA 3R', description: 'Non-fused AC disconnect, 60 A, NEMA 3R, lockable', unit: 'ea', price_usd: 85, specs: { rating_a: 60, nema: '3R', fused: false, lockable: true } },
  { id: 'dc-disconnect-60a-3r', category: 'disconnect', manufacturer: null, model: 'DC disconnect 60 A 600 V NEMA 3R', description: 'DC-rated disconnect, 60 A, 600 VDC, NEMA 3R', unit: 'ea', price_usd: 145, specs: { rating_a: 60, voltage_rating: 600, nema: '3R', dc_rated: true } },
  { id: 'breaker-2p-40a', category: 'ocpd', manufacturer: null, model: '2-pole 40 A breaker', description: 'Backfed 2-pole 40 A circuit breaker', unit: 'ea', price_usd: 45, specs: { poles: 2, rating_a: 40, note: 'Backfed breakers for interconnection do not require the 408.36(D) hold-down when the inverter is a utility-interactive listed unit — verify with the AHJ.' } },
  { id: 'breaker-2p-60a', category: 'ocpd', manufacturer: null, model: '2-pole 60 A breaker', description: 'Backfed 2-pole 60 A circuit breaker', unit: 'ea', price_usd: 55, specs: { poles: 2, rating_a: 60 } },
  { id: 'fuse-gpv-15a', category: 'ocpd', manufacturer: null, model: 'gPV fuse 15 A 1000 V', description: 'PV-rated midget fuse, 15 A, 1000 VDC', unit: 'ea', price_usd: 9, specs: { rating_a: 15, voltage_rating: 1000, type: 'gPV' } },
  { id: 'class-t-400a', category: 'ocpd', manufacturer: null, model: 'Class T fuse 400 A', description: 'Class T fuse and holder, 400 A, for battery bank protection', unit: 'ea', price_usd: 95, specs: { rating_a: 400, interrupt_rating_a: 20000, note: 'Class T is the standard choice for lithium banks because of the very high available fault current.' } },
  { id: 'spd-type2', category: 'ocpd', manufacturer: null, model: 'Type 2 SPD', description: 'Type 2 surge protective device for AC service', unit: 'ea', price_usd: 120, specs: { type: 2 } },
  { id: 'tigo-ts4-a-2f', category: 'rapid-shutdown', manufacturer: 'Tigo', model: 'TS4-A-2F', description: 'Module-level rapid shutdown device, 2 modules per unit', unit: 'ea', price_usd: 32, specs: { modules_per_unit: 2, note: 'Pairs with a Tigo RSS transmitter. Needed when the inverter has no integrated module-level shutdown.' } },
  { id: 'weeb-lug', category: 'grounding', manufacturer: null, model: 'WEEB grounding lug', description: 'Washer/lug bonding hardware for racking without integrated bonding', unit: 'ea', price_usd: 3.5, specs: { note: 'Not needed with UL 2703 racking that provides integrated bonding.' } },
  { id: 'ground-rod-8ft', category: 'grounding', manufacturer: null, model: 'Ground rod 8 ft', description: 'Copper-clad ground rod, 5/8 in x 8 ft, with acorn clamp', unit: 'ea', price_usd: 28, specs: { length_ft: 8 } },
  { id: 'label-set-nec', category: 'label', manufacturer: null, model: 'NEC PV label set', description: 'Engraved/reflective placard set: PV system disconnect, rapid shutdown, max DC voltage, multiple sources of power', unit: 'ea', price_usd: 45, specs: { note: 'Label content and colors changed between code cycles — the rapid shutdown switch label is white on red, reflective. Verify against the AHJ code edition.' } },
  { id: 'roof-flashing', category: 'misc', manufacturer: null, model: 'Roof flashing + sealant', description: 'Flashing and sealant per roof penetration', unit: 'ea', price_usd: 12, specs: {} },
  { id: 'ct-pair', category: 'monitoring', manufacturer: null, model: 'Current transformer pair', description: 'Split-core CTs for production and consumption monitoring', unit: 'ea', price_usd: 65, specs: {} },
]

export const catalog = {
  modules,
  inverters,
  batteries,
  chargeControllers,
  mounts,
  evse,
  loadCenters,
  bos,
}

export type Catalog = typeof catalog

/** Look up any catalogued part by id across every category. */
export function findPart(id: string) {
  for (const [category, list] of Object.entries(catalog)) {
    const hit = (list as Array<{ id: string }>).find((p) => p.id === id)
    if (hit) return { category, part: hit }
  }
  return null
}
